### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by hurricane2018** [kbatsos/CBMV#2]
hi, Thank you for your wonderful work. Can u provide the information of your dataset?

**Comment by kbatsos** [comment]
Hi, the dataset used for training is the Middlebury training dataset. I just provided the exact set as I used it for easier reproducibility of our results, but you can use the dataset as given form the original Middlebury 2014 source. Keep in mind that Middlebury also provides some extra stereo pairs that you need to downsample to half size to fit the half sized training data.

**Comment by hurricane2018** [comment]
Thank you very much !
